strategy:
  matrix:
    'Node 6': 
      versionSpec: '6.x'
    'Node 8': 
      versionSpec: '8.x'
    'Node 10': 
      versionSpec: '10.x'
    'Node 12': 
      versionSpec: '12.x'
    'Node 14': 
      versionSpec: '14.x'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(versionSpec)
  displayName: Install node

# install dependencies
- script: npm install
  displayName: npm install

# build
- script: npm run build
  displayName: npm run build

- script: npm run units
  displayName: npm run units

# publish build artifacts to drop folder so we can use them for release
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "_build"
    ArtifactName: "drop"
    ArtifactType: "Container"
  displayName: Publish build artifacts
